ENTITIES = {
    "weather": "weather.forecast_home",
    "outdoor_temp": "sensor.wohnzimmer_weather_station_outdoor_module_temperatur",
    "sun_rising": "sensor.sun_next_rising",
    "sun_setting": "sensor.sun_next_setting",
    "persons": [
        ("Mike", "person.mike_weber"),
        ("Franziska", "person.franziska_weber"),
        ("Lukas", "person.lukas_weber"),
        ("Anni", "person.anni_weber"),
    ],
    "windows": [
        ("Eingang", "binary_sensor.fb_heizung_eingang_fenster_auf"),
        ("Wohnzimmer", "binary_sensor.fb_heizung_wz_fenster_auf"),
    ],
    "power_now": "sensor.hausverbrauch_live",
    "energy_today": "sensor.emma_pv_ertrag_heute",
    "cost_today": "sensor.emma_gesamter_netzbezug_cost",
    "rooms": [
        ("Wohnzimmer", "sensor.wohnzimmer_weather_station_temperatur", None, None, None),
    ],
    "garbage": [],
    "vacation_start": None,
    "vacation_end": None,
    "vacation_label": None,
    "indoor_humidity": "sensor.wohnzimmer_weather_station_luftfeuchtigkeit",
    "grid_co2": "sensor.electricity_maps_co2_intensitat",
    "pressure": "sensor.wohnzimmer_weather_station_luftdruck",
    "calendars": ["calendar.familie_weber", "calendar.familywall", "calendar.zaoe_abfall"],

    "solar": {
        "pv_power":          "sensor.emma_pv_ausgangsleistung",
        "pv_today_kwh":      "sensor.emma_pv_ertrag_heute",
        "pv_total_kwh":      "sensor.emma_gesamte_pv_ertragsleistung",
        "house_load_w":      "sensor.hausverbrauch_live",
        "grid_w":            "sensor.emma_wirkleistung",
        "feed_today_kwh":    "sensor.emma_einspeisung_heute",
        "draw_today_kwh":    "sensor.emma_netzbezug_heute",
        "battery_soc":       "sensor.batterien_batterieladung",
        "battery_power":     "sensor.batterien_lade_entladeleistung",
        "battery_charge_today_kwh": "sensor.batterien_tagesladung",
        "battery_discharge_today_kwh": "sensor.batterien_tagesentladung",
        "wallbox_total_kwh": "sensor.wallbox_ladeenergie_clean",
        "wallbox_temp":      "sensor.wallbox_temperatur",
    },

    "pool": {
        "wassertemp":         "sensor.pool_wassertemperatur",
        "ph":                 "sensor.pool_ph",
        "orp":                "sensor.pool_orp",
        "filtration_h":       "sensor.pool_filtrationsempfehlung",
        "pumpe":              "switch.poolpumpe",
        "laufzeit_h":         "sensor.garten_poolpumpe_laufzeit_heute",
        "soll_h":             "input_number.pool_soll_stunden_heute",
        "manuell_aus":        "input_boolean.pool_manuell_heute_aus",
        "status":             "sensor.pool_steuerung_status",
        "messung_gultig":     "binary_sensor.pool_messung_gultig",
        "aktion_log":         "input_text.pool_aktion_log",
    },

    "miele": {
        "wm_phase":           "sensor.waschmaschine_programmphase",
        "wt_phase":           "sensor.waschetrockner_programmphase",
        "wm_finished":        "sensor.waschmaschine_fertig_um",
        "wt_finished":        "sensor.waschetrockner_fertig_um",
    },

    "vacuum": {
        "state":              "vacuum.roborock_qrevo_maxv_2",
        "status":             "sensor.roborock_qrevo_maxv_2_status",
    },

    "energy_subs": [
        ("Pool",      "sensor.garten_poolpumpe_energieverbrauch", "sensor.garten_poolpumpe_energieverbrauch", "sensor.garten_poolpumpe_kosten"),
        ("Wallbox",   "sensor.wallbox_ladeenergie_clean",          "sensor.wallbox_ladeenergie_clean",          "sensor.wallbox_ladekosten"),
    ],
    "co2_kumuliert": None,
    "co2_rate": None,
    "history_entities": [
        "sensor.wohnzimmer_weather_station_outdoor_module_temperatur",
        "sensor.wohnzimmer_weather_station_temperatur",
        "sensor.emma_pv_ausgangsleistung",
        "sensor.hausverbrauch_live",
        "sensor.batterien_batterieladung",
        "sensor.batterien_lade_entladeleistung",
        "sensor.pool_wassertemperatur",
        "sensor.pool_ph",
        "sensor.pool_orp",
        "sensor.unifi_gesamt_download",
        "sensor.unifi_gesamt_upload",
    ],
    "batteries": [],
    "backup_last": "sensor.backup_last_successful_automatic_backup",
    "backup_next": "sensor.backup_next_scheduled_automatic_backup",
    "thread_rssi_best": "sensor.thread_rssi_best",
    "thread_rssi_avg": "sensor.thread_rssi_avg",
    "thread_rssi_worst": "sensor.thread_rssi_worst",
    "sun_elevation_attr": "sun.sun",
    "internet_download": "sensor.unifi_gesamt_download",
    "internet_upload": "sensor.unifi_gesamt_upload",
    "internet_clients_prefix": "sensor.net_",
}
