ENTITIES = {
    "weather": "weather.forecast_home",
    "outdoor_temp": "sensor.aussentemperatur",
    "sun_rising": "sensor.sun_next_rising",
    "sun_setting": "sensor.sun_next_setting",
    "persons": [
        ("Robert", "person.robert"),
        ("Steffi", "person.steffi"),
        ("Oskar", "person.oskar"),
    ],
    "windows": [
        ("Wohnzimmer", "binary_sensor.fensterkontakt_wohnzimmer"),
        ("Küche", "binary_sensor.fensterkontakt_kueche"),
        ("Arbeitszimmer", "binary_sensor.eve_door_c550"),
        ("Schlafzimmer", "binary_sensor.fensterkontakt_schlafzimmer"),
        ("Oskar", "binary_sensor.fensterkontakt_oskar"),
        ("Luise", "binary_sensor.fensterkontakt_luise"),
        ("Bad", "binary_sensor.fensterkontakt_bad"),
    ],
    "power_now": "sensor.gesamtverbrauch_leistung",
    "energy_today": "sensor.gesamtverbrauch_energie_heute",
    "cost_today": "sensor.gesamtverbrauch_kosten_heute",
    "rooms": [
        ("Wohnzimmer",    "sensor.heizung_raumtemp_wohnzimmer",    "input_number.heizung_raumsoll_wohnzimmer",    "climate.eve_thermo_20ebp1701_4", "sensor.eve_thermo_20ebp1701_ventilstellung_4"),
        ("Schlafzimmer",  "sensor.heizung_raumtemp_schlafzimmer",  "input_number.heizung_raumsoll_schlafzimmer",  "climate.eve_thermo_20ebp1701_6", "sensor.eve_thermo_20ebp1701_ventilstellung_6"),
        ("Küche",         "sensor.heizung_raumtemp_kuche",         "input_number.heizung_raumsoll_kuche",         "climate.eve_thermo_20ebp1701",   "sensor.eve_thermo_20ebp1701_ventilstellung"),
        ("Arbeitszimmer", "sensor.heizung_raumtemp_arbeitszimmer", "input_number.heizung_raumsoll_arbeitszimmer", "climate.eve_thermo_20ebp1701_2", "sensor.eve_thermo_20ebp1701_ventilstellung_2"),
        ("Bad",           "sensor.heizung_raumtemp_bad",           "input_number.heizung_raumsoll_bad",           "climate.eve_thermo_20ebp1701_3", "sensor.eve_thermo_20ebp1701_ventilstellung_3"),
        ("Oskar",         "sensor.heizung_raumtemp_oskar",         "input_number.heizung_raumsoll_oskar",         "climate.eve_thermo_20ebp1701_7", "sensor.eve_thermo_20ebp1701_ventilstellung_7"),
        ("Luise",         "sensor.heizung_raumtemp_luise",         "input_number.heizung_raumsoll_luise",         "climate.eve_thermo_20ebp1701_5", "sensor.eve_thermo_20ebp1701_ventilstellung_5"),
    ],
    "garbage": [
        ("input_text.robert_mull_1_label", "input_datetime.robert_mull_1_start"),
        ("input_text.robert_mull_2_label", "input_datetime.robert_mull_2_start"),
        ("input_text.robert_mull_3_label", "input_datetime.robert_mull_3_start"),
    ],
    "vacation_start": "input_datetime.nachster_urlaub_start",
    "vacation_end": "input_datetime.nachster_urlaub_ende",
    "vacation_label": "input_text.nachster_urlaub_label",
    "indoor_humidity": "sensor.wohnzimmer_wand_luftfeuchtigkeit",
    "grid_co2": "sensor.electricity_maps_co2_intensitat",
    "pressure": "sensor.kueche_klima_luftdruck",
    "calendars": ["calendar.family", "calendar.privat", "calendar.arbeit"],
    "energy_subs": [
        ("Haus",      "sensor.shelly_analyzer_haus_haus_power",                       "sensor.shelly_analyzer_haus_haus_energy_today",                       "sensor.shelly_analyzer_haus_haus_cost_today"),
        ("Wallbox",   "sensor.shelly_analyzer_server_server_power",                   "sensor.shelly_analyzer_server_server_energy_today",                   "sensor.shelly_analyzer_server_server_cost_today"),
        ("Boiler",    "sensor.shelly_analyzer_warmwasserboiler_warmwasserboiler_power", "sensor.shelly_analyzer_warmwasserboiler_warmwasserboiler_energy_today", "sensor.shelly_analyzer_warmwasserboiler_warmwasserboiler_cost_today"),
        ("Weihnacht", "sensor.shelly_analyzer_weihnachtslicht_weihnachtslicht_power", "sensor.shelly_analyzer_weihnachtslicht_weihnachtslicht_energy_today", "sensor.shelly_analyzer_weihnachtslicht_weihnachtslicht_cost_today"),
    ],
    "co2_kumuliert": "sensor.co2_kumuliert",
    "co2_rate": "sensor.gesamt_co2_rate",
    "history_entities": [
        "sensor.aussentemperatur",
        "sensor.heizung_raumtemp_wohnzimmer",
        "sensor.heizung_raumtemp_schlafzimmer",
        "sensor.heizung_raumtemp_kuche",
        "sensor.heizung_raumtemp_arbeitszimmer",
        "sensor.heizung_raumtemp_bad",
        "sensor.heizung_raumtemp_oskar",
        "sensor.heizung_raumtemp_luise",
        "sensor.shelly_analyzer_haus_haus_power",
        "sensor.shelly_analyzer_server_server_power",
        "sensor.shelly_analyzer_warmwasserboiler_warmwasserboiler_power",
        "sensor.shelly_analyzer_weihnachtslicht_weihnachtslicht_power",
        "sensor.unifi_gesamt_download",
        "sensor.unifi_gesamt_upload",
    ],
    "batteries": [
        ("TRV Wohnzimmer",    "sensor.eve_thermo_20ebp1701_batterie_4",      "trv"),
        ("TRV Schlafzimmer",  "sensor.eve_thermo_20ebp1701_batterie_6",      "trv"),
        ("TRV Küche",         "sensor.eve_thermo_20ebp1701_batterie",        "trv"),
        ("TRV Arbeitszimmer", "sensor.eve_thermo_20ebp1701_batterie_2",      "trv"),
        ("TRV Bad",           "sensor.eve_thermo_20ebp1701_batterie_3",      "trv"),
        ("TRV Oskar",         "sensor.eve_thermo_20ebp1701_batterie_7",      "trv"),
        ("TRV Luise",         "sensor.eve_thermo_20ebp1701_batterie_5",      "trv"),
        ("Fenster Wohnzimmer","sensor.fensterkontakt_wohnzimmer_batterie",   "window"),
        ("Fenster Schlafzimmer","sensor.fensterkontakt_schlafzimmer_batterie","window"),
        ("Fenster Küche",     "sensor.fensterkontakt_kueche_batterie",       "window"),
        ("Fenster Bad",       "sensor.eve_door_20ebn9901_batterie",          "window"),
        ("Fenster Oskar",     "sensor.fensterkontakt_oskar_batterie",        "window"),
        ("Fenster Luise",     "sensor.fensterkontakt_luise_batterie",        "window"),
        ("Dimmer SZ Links",   "sensor.dimmer_schlafzimmer_links_batterie",   "dimmer"),
        ("Dimmer SZ Rechts",  "sensor.dimmer_schlafzimmer_rechts_batterie",  "dimmer"),
        ("Dimmer WZ Couch",   "sensor.dimmer_wohnzimmer_couch_batterie",     "dimmer"),
        ("Küche Schalter",    "sensor.kuche_schalter_batterie",              "dimmer"),
        ("WZ Klima",          "sensor.wohnzimmer_wand_batterie",             "klima"),
        ("Küche Klima",       "sensor.kueche_klima_batterie",                "klima"),
    ],
    "backup_last": "sensor.backup_last_successful_automatic_backup",
    "backup_next": "sensor.backup_next_scheduled_automatic_backup",
    "thread_rssi_best": "sensor.thread_rssi_best",
    "thread_rssi_avg": "sensor.thread_rssi_avg",
    "thread_rssi_worst": "sensor.thread_rssi_worst",
    "sun_elevation_attr": "sun.sun",
    "internet_download": "sensor.unifi_gesamt_download",
    "internet_upload": "sensor.unifi_gesamt_upload",
    "internet_clients_prefix": "sensor.net_",
}
